version = 1
SPDX-PackageName = "Gardener website"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/website"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2025 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "The generated website code contains various different licenses which take predecense over the bulk licensing defined here."

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2025 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "The generated website code contains various different licenses which take predecense over the bulk licensing defined here."
