#!/bin/ash

if [[ -z "${GARDENER_WEBSITE_PATH}" ]]; then
  echo "GARDENER_WEBSITE_PATH not set"
  exit 1
fi

cd ${GARDENER_WEBSITE_PATH}
npm install
node ./node/index.js
cd hugo
../binaries/hugo version
../binaries/hugo --destination ../docs
cd -
node ./node/index.js clean


git add . -A
git commit -m 'Automatic build triggered by last commit [skip ci]'